name: Build and test project

on:
  push:
    branches: ["*"]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Go Test
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Check Test Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/lucaschain/beholder
          threshold-total: 80

          git-token: ${{ github.ref_name == 'main' && secrets.GH_TOKEN || '' }}
          git-branch: badges

  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run Lint
        uses: Jerome1337/gofmt-action@v1.0.5
