name: Check test coverage

on:
  push:
    branches: ["*"]

jobs:
  check-coverage:
    name: Check Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/lucaschain/beholder
          threshold-total: 80

          git-token: ${{ github.ref_name == 'main' && secrets.GH_TOKEN || '' }}
          git-branch: badges
